// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/market-items/": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market_items_admin"
                ],
                "summary": "Create Market Item (Admin)",
                "operationId": "create_market_item_admin",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_marketplace_admin.MarketItemAdminCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_marketplace_admin.MarketItemAdminResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/market-items/{itemId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market_items_admin"
                ],
                "summary": "Get Market Item by ID (Admin)",
                "operationId": "detail_market_item_admin",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_marketplace_admin.MarketItemAdminResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market_items_admin"
                ],
                "summary": "Update Market Item (Admin)",
                "operationId": "update_market_item_admin",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_marketplace_admin.MarketItemAdminUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_marketplace_admin.MarketItemAdminResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/series/": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lego_series_admin"
                ],
                "summary": "Create LEGO Series object",
                "operationId": "create_series",
                "parameters": [
                    {
                        "description": "create data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_lego.LegoSeriesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/series/{seriesID}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lego_series_admin"
                ],
                "summary": "Delete LegoSeries object",
                "operationId": "delete_series",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "series ID",
                        "name": "seriesID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/sets/": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lego_sets_admin"
                ],
                "summary": "Create Lego Set object",
                "operationId": "set_create",
                "parameters": [
                    {
                        "description": "create data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_lego.LegoSetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/sets/{setID}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lego_sets_admin"
                ],
                "summary": "Delete Lego Set object",
                "operationId": "set_delete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LegoSet ID",
                        "name": "setID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/users/": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users_admin"
                ],
                "summary": "Get Users (Admin)",
                "operationId": "list_users_admin",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users_admin.UserAdminDetailResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/users/register": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users_admin"
                ],
                "summary": "Create Admin",
                "operationId": "create-admin",
                "parameters": [
                    {
                        "description": "reg request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users_admin.AdminRegistrationRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users_admin.AdminRegistrationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/users/{userId}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users_admin"
                ],
                "summary": "Get User by ID (Admin)",
                "operationId": "detail_user_admin",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users_admin.UserAdminDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users_admin"
                ],
                "summary": "Update User",
                "operationId": "update_user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users_admin.UserAdminUpdateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users_admin.UserAdminDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users_admin"
                ],
                "summary": "Delete User",
                "operationId": "delete_user_admin",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/collections/": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_collections"
                ],
                "summary": "Get User Collection",
                "operationId": "get_user_collection",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_collections.UserLegoSetCollectionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_collections"
                ],
                "summary": "Add Set To Collection",
                "operationId": "add_set_user_collections",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_collections.CollectionLegoSetAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/collections/valuation/{currencyID}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_collections"
                ],
                "summary": "Get User Collection Valuation",
                "operationId": "get_user_collection_valuation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "currency ID",
                        "name": "currencyID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_collections.UserCollectionValuationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/collections/{setID}": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_collections"
                ],
                "summary": "Update Collection Set Info",
                "operationId": "update_set_user_collection",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "set ID",
                        "name": "setID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_collections.CollectionLegoSetUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_collections"
                ],
                "summary": "Delete User Collection Set",
                "operationId": "delete_set_user_collections",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "set ID",
                        "name": "setID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/market-items/": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market_items"
                ],
                "summary": "Get Market Items",
                "operationId": "list_market_items",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market_items"
                ],
                "summary": "Create Market Item",
                "operationId": "create_market_item",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_marketplace.MarketItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/market-items/authorized/": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market_items"
                ],
                "summary": "Get Market Items Authorized",
                "operationId": "list_market_items_authorized",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/market-items/{itemID}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market_items"
                ],
                "summary": "Get Market Item",
                "operationId": "detail_market_item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "item ID",
                        "name": "itemID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_marketplace.MarketItemResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market_items"
                ],
                "summary": "Update Market Item",
                "operationId": "update_market_item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "item ID",
                        "name": "itemID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_marketplace.MarketItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_marketplace.MarketItemResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/market-items/{itemId}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "market_items"
                ],
                "summary": "Delete Market Item",
                "operationId": "delete_market_item",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "item ID",
                        "name": "itemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/series/": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lego_series"
                ],
                "summary": "List of LEGO Series objects",
                "operationId": "list_lego_series",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_lego.LegoSeriesResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/series/{seriesID}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lego_series"
                ],
                "summary": "LEGO Series by id",
                "operationId": "detail_lego_series",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "series ID",
                        "name": "seriesID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_lego.LegoSeriesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/sets/": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lego_sets"
                ],
                "summary": "List of LegoSet objects",
                "operationId": "list_sets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_lego.LegoSetResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/sets/{setID}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lego_sets"
                ],
                "summary": "Get LegoSet by ID",
                "operationId": "set_detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Lego Set ID",
                        "name": "setID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_lego.LegoSetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/auth/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "register new user",
                "operationId": "user-register",
                "parameters": [
                    {
                        "description": "user data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserRegistrationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/auth/token": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "generate jwt token",
                "operationId": "create-jwt",
                "parameters": [
                    {
                        "description": "jwt request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.JWTRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.JWTResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/images/:userID": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users_images"
                ],
                "summary": "Get User Images List",
                "operationId": "get_user_images",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserImagesListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users_images"
                ],
                "summary": "Download User Image",
                "operationId": "upload_user_image",
                "parameters": [
                    {
                        "type": "file",
                        "description": "filepath",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserImageUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/images/download": {
            "get": {
                "tags": [
                    "users_images"
                ],
                "summary": "Download User Image",
                "operationId": "download_user_image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filepath",
                        "name": "fp",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/profile/{userID}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_profile_pages"
                ],
                "summary": "Get User Profile Page",
                "operationId": "detail_user_profile_page",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users_profile.UserProfilePageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/reviews/": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_reviews"
                ],
                "summary": "Get User Reviews",
                "operationId": "list_user_reviews",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_reviews"
                ],
                "summary": "Create User Review",
                "operationId": "create_user_review",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/reviews/{reviewID}": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_reviews"
                ],
                "summary": "Get User Review",
                "operationId": "detail_user_review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "review ID",
                        "name": "reviewID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/reviews/{reviewId}": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_reviews"
                ],
                "summary": "Delete User Review",
                "operationId": "delete_user_review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "review ID",
                        "name": "reviewId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "legocy-go_internal_delivery_http_resources.DataMetaResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {}
            }
        },
        "legocy-go_internal_delivery_http_resources_collections.CollectionLegoSetAddRequest": {
            "type": "object",
            "properties": {
                "buy_price": {
                    "type": "number"
                },
                "lego_set_id": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_collections.CollectionLegoSetResponse": {
            "type": "object",
            "properties": {
                "buy_price": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "lego_set": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_lego.LegoSetResponse"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_collections.CollectionLegoSetUpdateRequest": {
            "type": "object",
            "properties": {
                "buy_price": {
                    "type": "number"
                },
                "lego_set_id": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_collections.UserCollectionValuationResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "number"
                },
                "user": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserDetailResponse"
                },
                "valuations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_valuation.LegoSetValuationResponse"
                    }
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_collections.UserLegoSetCollectionResponse": {
            "type": "object",
            "properties": {
                "collection_sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_collections.CollectionLegoSetResponse"
                    }
                },
                "user": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserDetailResponse"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_lego.LegoSeriesRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_lego.LegoSeriesResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_lego.LegoSetRequest": {
            "type": "object",
            "properties": {
                "n_pieces": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "series_id": {
                    "type": "integer"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_lego.LegoSetResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "n_pieces": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "series": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_lego.LegoSeriesResponse"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_marketplace.MarketItemRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "lego_set_id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "set_state": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_marketplace.MarketItemResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lego_set": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_lego.LegoSetResponse"
                },
                "location": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "seller": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserDetailResponse"
                },
                "set_state": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_marketplace_admin.MarketItemAdminCreateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "lego_set_id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "seller_id": {
                    "type": "integer"
                },
                "set_state": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_marketplace_admin.MarketItemAdminResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lego_set": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_lego.LegoSetResponse"
                },
                "location": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "seller": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserDetailResponse"
                },
                "set_state": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_marketplace_admin.MarketItemAdminUpdateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "lego_set_id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "seller_id": {
                    "type": "integer"
                },
                "set_state": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users.JWTRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users.JWTResponse": {
            "type": "object",
            "properties": {
                "access": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users.UserDetailResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users.UserImageInfoResponse": {
            "type": "object",
            "properties": {
                "downloadURL": {
                    "type": "string"
                },
                "filepath": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users.UserImageUploadResponse": {
            "type": "object",
            "properties": {
                "imageURL": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users.UserImagesListResponse": {
            "type": "object",
            "properties": {
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserImageInfoResponse"
                    }
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users.UserRegistrationRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users.UserRegistrationResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users.UserReviewRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "seller_id": {
                    "type": "integer"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users.UserReviewResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "reviewer": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserDetailResponse"
                },
                "seller": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserDetailResponse"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users_admin.AdminRegistrationRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users_admin.AdminRegistrationResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users_admin.UserAdminDetailResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users_admin.UserAdminUpdateRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "description": "Admin/User/etc.",
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_users_profile.UserProfilePageResponse": {
            "type": "object",
            "properties": {
                "marketItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_marketplace.MarketItemResponse"
                    }
                },
                "user": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserDetailResponse"
                },
                "userImages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserImageInfoResponse"
                    }
                },
                "userReviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_users.UserReviewResponse"
                    }
                }
            }
        },
        "legocy-go_internal_delivery_http_resources_valuation.LegoSetValuationResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "lego_set": {
                    "$ref": "#/definitions/legocy-go_internal_delivery_http_resources_lego.LegoSetResponse"
                },
                "state": {
                    "type": "string"
                },
                "valuation": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "LEGOcy API",
	Description:      "LEGOcy is a marketplace for LEGO lovers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
